Failed to create password reset token for ibehemmanuel32@gmail.com: no such table: django_rest_passwordreset_resetpasswordtoken
Internal Server Error: /account/password_reset/request/
Failed to create password reset token for ibehemmanuel32@gmail.com: no such table: django_rest_passwordreset_resetpasswordtoken
Internal Server Error: /account/password_reset/
Failed to create password reset token for ibehemmanuel32@gmail.com: no such table: django_rest_passwordreset_resetpasswordtoken
Internal Server Error: /account/password_reset/
Failed to create password reset token for ibehemmanuel32@gmail.com: no such table: django_rest_passwordreset_resetpasswordtoken
Internal Server Error: /account/password_reset/
Failed to create password reset token for ibehemmanuel32@gmail.com: no such table: django_rest_passwordreset_resetpasswordtoken
Internal Server Error: /account/password_reset/
Failed to create password reset token for ibehemmanuel32@gmail.com: no such table: django_rest_passwordreset_resetpasswordtoken
Internal Server Error: /account/password_reset/
Failed to create password reset token for ibehemmanuel32@gmail.com: no such table: django_rest_passwordreset_resetpasswordtoken
Internal Server Error: /account/password_reset/
Failed to create password reset token for ibehemmanuel32@gmail.com: no such table: django_rest_passwordreset_resetpasswordtoken
Internal Server Error: /account/password_reset/
Failed to create password reset token for ibehemmanuel32@gmail.com: name 'reset_password_token_created' is not defined
Internal Server Error: /account/password_reset/
Internal Server Error: /account/verify_code/
Traceback (most recent call last):
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\bitphyte\account\views.py", line 86, in code_verification
    user.save()
    ~~~~~~~~~^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\bitphyte\account\models.py", line 80, in save
    super(User, self).save(*args, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\contrib\auth\base_user.py", line 65, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\db\models\base.py", line 1023, in save_base
    post_save.send(
    ~~~~~~~~~~~~~~^
        sender=origin,
        ^^^^^^^^^^^^^^
    ...<4 lines>...
        using=using,
        ^^^^^^^^^^^^
    )
    ^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\bitphyte\account\signals.py", line 70, in send_welcome_email
    text_content = render_to_string('email/welcome_email.txt', context)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: email/welcome_email.txt
Internal Server Error: /management/referral-details/
Traceback (most recent call last):
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\bitphyte\management\views.py", line 33, in get_referral_details
    return Response(serializer.data, status=status.HTTP_200_OK)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\rest_framework\serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\rest_framework\serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\rest_framework\serializers.py", line 716, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\rest_framework\serializers.py", line 525, in to_representation
    for field in fields:
                 ^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\rest_framework\serializers.py", line 386, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\rest_framework\serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\rest_framework\serializers.py", line 1081, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\rest_framework\serializers.py", line 1177, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'referee_details' was declared on serializer ReferralSerializer, but has not been included in the 'fields' option.
Internal Server Error: /admin/payment/balance/
Traceback (most recent call last):
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'referral_bonus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\contrib\admin\utils.py", line 290, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\contrib\admin\utils.py", line 330, in _get_non_gfk_field
    field = opts.get_field(name)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\db\models\options.py", line 685, in get_field
    raise FieldDoesNotExist(
        "%s has no field named '%s'" % (self.object_name, field_name)
    )
django.core.exceptions.FieldDoesNotExist: Balance has no field named 'referral_bonus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\library.py", line 359, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 354, in result_list
    "results": list(results(cl)),
               ~~~~^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 330, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 321, in __init__
    super().__init__(*items)
    ~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 219, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\contrib\admin\utils.py", line 299, in lookup_field
    value = attr(obj)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\bitphyte\payment\admin.py", line 21, in referral_bonus
    return obj.referral_bonus
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\bitphyte\payment\models.py", line 130, in referral_bonus
    profile = self.user.profile  # Make sure this is the UserProfile
              ^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'profile'
Internal Server Error: /admin/payment/balance/
Traceback (most recent call last):
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'total_amount_accumulated'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\contrib\admin\utils.py", line 290, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\contrib\admin\utils.py", line 330, in _get_non_gfk_field
    field = opts.get_field(name)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\db\models\options.py", line 685, in get_field
    raise FieldDoesNotExist(
        "%s has no field named '%s'" % (self.object_name, field_name)
    )
django.core.exceptions.FieldDoesNotExist: Balance has no field named 'total_amount_accumulated'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\template\library.py", line 359, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 354, in result_list
    "results": list(results(cl)),
               ~~~~^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 330, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 321, in __init__
    super().__init__(*items)
    ~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 219, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\contrib\admin\utils.py", line 299, in lookup_field
    value = attr(obj)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\bitphyte\payment\admin.py", line 24, in total_amount_accumulated
    return obj.total_amount_accumulated
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Balance' object has no attribute 'total_amount_accumulated'
Internal Server Error: /admin/payment/dailyinterestaccrual/
Traceback (most recent call last):
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: payment_dailyinterestaccrual.payment_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\contrib\admin\options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\contrib\admin\sites.py", line 246, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\contrib\admin\options.py", line 2163, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ~~~^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\backendbit\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: payment_dailyinterestaccrual.payment_id
